name: Unit tests
on: [push, pull_request]
jobs:
  containers-tests-job:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/opensuse/bci/nodejs:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps and run unit tests
        run: |
          echo "Job started by ${{ github.event_name }}"
          echo "Running on ${{ runner.os }}"
          ip link
          echo "Sources checked out"
          echo "Fetching deps"
          npm ci
          npm run test

